version: '3.8'
services:
    php-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: arkusnexus-backend
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
    web-server:
        image: nginx:1.23.3-alpine
        container_name: arkusnexus-server
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
